// Crack passwords using brute force
// Raphael Uziel
// July 23, 2018
// Problem set 2

#define _XOPEN_SOURCE
#include <cs50.h>
#include <stdio.h>
#include <unistd.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

// Constants showing number of permutations using 1, 2, 3, 4, or 5
// alphabetic characters (A - Z and a-z).
#define NP1 52
#define NP2 NP1 + 52*52
#define NP3 NP2 + 52*52*52
#define NP4 NP3 + 52*52*52*52

int main(int argc, string argv[])
{
    char salt[] = "AB";
    char key[] = { 'A', '\0', '\0', '\0', '\0', '\0' };

    // User begins program passing their password value to main
    if (argc == 2)
    {
        salt[0] = argv[1][0];
        salt[1] = argv[1][1];
    }
    else
    {
        printf("Usage: ./crack hash\n");
        return 1;
    }

    int count = 0;

    // Generate a five character password guess from 'A' to 'zzzzz'
    // The compare the hash generated by the crypt function to the
    // one submitted by the user
    for (int i = 'A'; i <= 'z'; i++)
    {
        // Skip non alphabetical characters
        if (i == 'Z' + 1)
        {
            i = 'a';
        }
        for (int j = 'A'; j <= 'z'; j++)
        {
            if (j == 'Z' + 1)
            {
                j = 'a';
            }
            for (int k = 'A'; k <= 'z'; k++)
            {
                if (k == 'Z' + 1)
                {
                    k = 'a';
                }
                for (int l = 'A'; l <= 'z'; l++)
                {
                    if (l == 'Z' + 1)
                    {
                        l = 'a';
                    }
                    for (int m = 'A'; m <= 'z'; m++)
                    {
                        if (m == 'Z' + 1)
                        {
                            m = 'a';
                        }
                        count++;
                        key[0] = m;
                        if (count == NP1 + 1)
                        {
                            l = 'A';
                        }
                        if (count == NP2 + 1)
                        {
                            k = 'A';
                            l = 'A';
                        }
                        if (count == NP3 + 1)
                        {
                            j = 'A';
                            k = 'A';
                            l = 'A';
                        }
                        if (count == NP4 + 1)
                        {
                            i = 'A';
                            j = 'A';
                            k = 'A';
                            l = 'A';
                        }

                        if (count > NP1)  // Now to passwords with two characters
                        {
                            key[1] = l;
                        }
                        else
                        {
                            key[1] = '\0';
                        }
                        if (count > NP2) // Add third character
                        {
                            key[2] = k;
                        }
                        else
                        {
                            key[2] = '\0';
                        }
                        if (count > NP3) // Add fourth character
                        {
                            key[3] = j;
                        }
                        else
                        {
                            key[3] = '\0';
                        }
                        if (count > NP4) // Add the fifth character
                        {
                            key[4] = i;
                        }
                        else
                        {
                            key[4] = '\0';
                        }

                        // Compare hash generated by crypt to one entered by user
                        if (strcmp(crypt(key, salt), argv[1]) == 0)
                        {
                            printf("%s\n", key);
                            return 0;
                        }
                    }
                }
            }
        }
    }
}