CREATE TABLE 'users' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'username' TEXT NOT NULL, 'hash' TEXT NOT NULL, 'cash' NUMERIC NOT NULL DEFAULT 10000.00 );
CREATE TABLE 'portfolio' ('transaction_id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'user' TEXT NOT NULL, 'symbol' TEXT NOT NULL, 'name' TEXT NOT NULL, 'shares' INTEGER NOT NULL, 'price' NUMERIC NOT NULL, 'total' NUMERIC NOT NULL, 'transacted' DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE 'holdings' ('user' TEXT NOT NULL, 'symbol' TEXT PRIMARY KEY NOT NULL, 'shares_owned' INTEGER NOT NULL, 'name' TEXT, 'price' NUMERIC, 'total' INTEGER);
CREATE UNIQUE INDEX 'username' ON "users" ("username");
